name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Ensure go mod tidy has zero output
        run: go mod tidy -v && git diff --exit-code

      - name: Install go-cover-treemap
        run: go install github.com/nikolaydubina/go-cover-treemap@latest

      - name: Run integration tests with coverage
        run: |
          mkdir -p docs
          COVERPKG=$(go list ./internal/... | paste -sd, -)
          go test -v -coverpkg=$COVERPKG -coverprofile=cover.out ./tests/integration_tests
          go-cover-treemap -percent=true -w=1080 -h=360 -coverprofile=cover.out > docs/coverage.svg

      - name: Commit and push coverage SVG to repo
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add docs/coverage.svg
          git commit -m "Update coverage report [skip ci]" || echo "No changes to commit"
          git push origin main